apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-training.fullname" . }}
  labels:
    app: {{ include "devops-training.name" . }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "devops-training.name" . }}
