# CHANGEMENT PORTABILITÉ :
# - path corrigé de /* à / pour compatibilité Kubernetes standard
# - pathType changé en Prefix
# - annotations GCP supprimées
# Pour rollback, remettre l'ancien path et pathType, et réajouter les annotations si besoin.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vault.walidbensmida.com
      secretName: vault-walidbensmida-com-tls
  rules:
    - host: vault.walidbensmida.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
