server:
  port: 8081

spring:
  application:
    name: devops-training
  cloud:
    vault:
      uri: http://vault:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN}   # <= Ici : VAULT_TOKEN injecté comme ENV
      kv:
        enabled: true
        backend: secret
        default-context: application

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Configuration Vault (si tu le réactives plus tard, mais peut être retiré pour l'instant)
# vault:
#   uri: http://127.0.0.1:8200
#   token: ${VAULT_TOKEN}

# Sécurité : peut être gérée dans le code Java (SecurityFilterChain)
