server:
  port: 8081

spring:
  application:
    name: devops-training
  config:
    import: vault://
  cloud:
    vault:
      uri: http://host.docker.internal:8200
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        application-name: app
      ssl:
        verify: false