# ServiceAccount dédié à Jenkins
# Ce compte de service est utilisé par le déploiement Jenkins pour bénéficier des droits RBAC définis dans le fichier jenkins-job-rbac.yaml.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default
