apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-training
  template:
    metadata:
      labels:
        app: devops-training
    spec:
      containers:
        - name: devops-training
          image: walidbensmida/devops-training:v13
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token-secret
                  key: VAULT_TOKEN
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10

