# CHANGEMENT PORTABILITÉ :
# - Annotations GCP supprimées
# - path corrigé de /* à / pour compatibilité Kubernetes standard
# - pathType changé en Prefix
# Pour rollback, remettre les annotations et l'ancien path/pathType si besoin.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-training-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - walidbensmida.com
      secretName: walidbensmida-com-tls
  rules:
    - host: walidbensmida.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-training
                port:
                  number: 8081
# FIN CHANGEMENT PORTABILITÉ
