apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-training-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: my-static-ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: devops-training
                port:
                  number: 8081
